---
http_interactions:
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/users/00u6nm9ytbmwHeunx0h7
    body:
      encoding: UTF-8
      string: '{"profile":{}}'
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 200
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 04:35:36 GMT
      server:
      - nginx
      content-type:
      - application/json;charset=UTF-8
      vary:
      - Accept-Encoding
      x-okta-request-id:
      - V4cWmEkS67yJuNE68sz@tAAABWA
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1198'
      x-rate-limit-reset:
      - '1468470966'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      strict-transport-security:
      - max-age=315360000
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=CB45EA49044D8FBB121125C7516ACE87;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00u6nm9ytbmwHeunx0h7","externalId":null,"created":"2016-07-14T04:35:36.000Z","lastUpdated":"2016-07-14T04:35:36.000Z","scope":"USER","status":"ACTIVE","statusChanged":"2016-07-14T04:35:36.000Z","passwordChanged":null,"syncState":"DISABLED","lastSync":null,"credentials":{"userName":"julian@example.com"},"profile":{},"_links":{"app":{"href":"https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7"},"user":{"href":"https://okta-test.okta.com/api/v1/users/00u6nm9ytbmwHeunx0h7"}}}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 04:35:36 GMT
- request:
    method: post
    uri: https://okta-test.okta.com/api/v1/apps/0oa6nmg6fdvwvoHwR0h7/users/00u6o0w6tyuPVEeZr0h7
    body:
      encoding: UTF-8
      string: '{"profile":{}}'
    headers:
      User-Agent:
      - Oktakit v0.1.0
      Accept:
      - application/json
      Content-Type:
      - application/json
      Authorization:
      - SSWS  <<ACCESS_TOKEN>>
  response:
    status:
      code: 500
      message: 
    headers:
      date:
      - Thu, 14 Jul 2016 13:53:23 GMT
      server:
      - nginx
      content-type:
      - application/json
      x-okta-request-id:
      - V4eZU@kF-t6HOvQdBAXk2gAABrw
      x-rate-limit-limit:
      - '1200'
      x-rate-limit-remaining:
      - '1197'
      x-rate-limit-reset:
      - '1468504415'
      p3p:
      - CP="HONK"
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      expires:
      - '0'
      set-cookie:
      - sid=""; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/, JSESSIONID=3712D176245063D5A6B2CB6B17121440;
        Path=/
      connection:
      - close
      transfer-encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"errorCode":"E0000009","errorSummary":"Internal Server Error","errorLink":"E0000009","errorId":"oaeRfXqvZguSZWPScoNamCD3A","errorCauses":[]}'
    http_version: 
  recorded_at: Thu, 14 Jul 2016 13:53:23 GMT
recorded_with: VCR 3.0.3
